version: '3'

services:
  postgres-raw:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_RAW_PASSWORD}
    ports:
      - ${POSTGRES_RAW_HOST_PORT}:5432
    volumes:
      - ${POSTGRES_RAW_HOST_PATH}:${POSTGRES_RAW_CONTAINER_PATH}

  postgres-transformed:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_TRANSFORMED_PASSWORD}
    ports:
      - ${POSTGRES_TRANSFORMED_HOST_PORT}:5432
    volumes:
      - ${POSTGRES_TRANSFORMED_HOST_PATH}:${POSTGRES_TRANSFORMED_CONTAINER_PATH}

  airbyte:
    image: airbyte/airbyte
    environment:
      AIRBYTE_API_KEY: ${AIRBYTE_API_KEY}
      AIRBYTE_ENCRYPTION_KEY: ${AIRBYTE_ENCRYPTION_KEY}
    ports:
      - ${AIRBYTE_HOST_PORT}:8000
