version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - ${POSTGRES_HOST_PATH}:${POSTGRES_CONTAINER_PATH}